# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set the default environment variables
ENV MONGO_INITDB_ROOT_USERNAME=anvesh
ENV MONGO_INITDB_ROOT_PASSWORD=Anv1997

# Expose the default MongoDB port
EXPOSE 27017

# Default command to run MongoDB
CMD ["mongod"]
