version: '3.8'

services:
  mongodb:
    build: .
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: anvesh
      MONGO_INITDB_ROOT_PASSWORD: Anv1997
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
